# STEAM32 ID 可通过网站查询 https://steamid.xyz/
CONFIG_STEAMID = 0

# http代理
HTTP_PROXY = {
    # 'http': '127.0.0.1:8008'
}

# 修改开关 / Modify switch
# modify_heroEquipmentLevel 修改遗物等级
# modify_TOTEMLevel 修改图腾等级
# modify_SPARCOIN 增加或减少钻石
# modify_TREASURES 修改宝物
ALLMIGHT = {
    "modify_heroEquipmentLevel": True,
    "modify_TOTEMLevel": True,
    "modify_SPARCOIN": True,
    "modify_TREASURES": True
}

# 英雄遗物等级 / Hero equipment level
CONFIG_heroEquipmentLevel = {
    "heroEquipmentHead": 50,
    "heroEquipmentArmor": 50,
    "heroEquipmentLegguard": 50,
    "heroEquipmentLeg": 50,
    "heroEquipmentShoes": 50,
    "heroEquipmentMainweapon": 50,
    "heroEquipmentSpeciaiweapon": 50
}

# 增加或减少钻石数量 / Increase or decrease sparcoin quantity
CONFIG_SPARCOIN = 0

# 图腾最大等级为 50，totemBwLevel、totemSwLevel、totemYxLevel 最大等级为 1
# totem MaxLevel 50
# totemBwLevel、totemSwLevel、totemYxLevel MaxLevel 1
CONFIG_TOTEM = {
    "totemAyLevel": 50,
    "totemBwLevel": 1,
    "totemCfLevel": 50,
    "totemDjLevel": 50,
    "totemDzLevel": 50,
    "totemFyLevel": 50,
    "totemJhLevel": 50,
    "totemMhLevel": 50,
    "totemMlLevel": 50,
    "totemSdLevel": 50,
    "totemSjLevel": 50,
    "totemSmLevel": 50,
    "totemSwLevel": 1,
    "totemYxLevel": 1,
    "totemZfLevel": 50
}

# 添加宝物在后面加 {"treasureNumber": 1, "treasureId": 1} 修改 treasureId 为宝物ID
# Add the treasure code to the CONFIG_TREASURES, modify the treasureId
CONFIG_TREASURES = [{"treasureNumber": 1, "treasureId": 1}, {"treasureNumber": 1, "treasureId": 2},
                    {"treasureNumber": 1, "treasureId": 3}, {"treasureNumber": 1, "treasureId": 4},
                    {"treasureNumber": 1, "treasureId": 5}, {"treasureNumber": 1, "treasureId": 6},
                    {"treasureNumber": 1, "treasureId": 7}, {"treasureNumber": 1, "treasureId": 8},
                    {"treasureNumber": 1, "treasureId": 9}, {"treasureNumber": 1, "treasureId": 10},
                    {"treasureNumber": 1, "treasureId": 11}, {"treasureNumber": 1, "treasureId": 12},
                    {"treasureNumber": 1, "treasureId": 13}, {"treasureNumber": 1, "treasureId": 14},
                    {"treasureNumber": 1, "treasureId": 15}, {"treasureNumber": 1, "treasureId": 16},
                    {"treasureNumber": 1, "treasureId": 17}, {"treasureNumber": 1, "treasureId": 18},
                    {"treasureNumber": 1, "treasureId": 19}, {"treasureNumber": 1, "treasureId": 20},
                    {"treasureNumber": 1, "treasureId": 21}, {"treasureNumber": 1, "treasureId": 22},
                    {"treasureNumber": 1, "treasureId": 23}, {"treasureNumber": 1, "treasureId": 24},
                    {"treasureNumber": 1, "treasureId": 25}, {"treasureNumber": 1, "treasureId": 26},
                    {"treasureNumber": 1, "treasureId": 27}, {"treasureNumber": 1, "treasureId": 28},
                    {"treasureNumber": 1, "treasureId": 29}, {"treasureNumber": 1, "treasureId": 30},
                    {"treasureNumber": 1, "treasureId": 31}, {"treasureNumber": 1, "treasureId": 32},
                    {"treasureNumber": 1, "treasureId": 33}, {"treasureNumber": 1, "treasureId": 34},
                    {"treasureNumber": 1, "treasureId": 35}, {"treasureNumber": 1, "treasureId": 36},
                    {"treasureNumber": 1, "treasureId": 37}, {"treasureNumber": 1, "treasureId": 38},
                    {"treasureNumber": 1, "treasureId": 39}, {"treasureNumber": 1, "treasureId": 40},
                    {"treasureNumber": 1, "treasureId": 41}, {"treasureNumber": 1, "treasureId": 42},
                    {"treasureNumber": 1, "treasureId": 43}, {"treasureNumber": 1, "treasureId": 44},
                    {"treasureNumber": 1, "treasureId": 45}, {"treasureNumber": 1, "treasureId": 46},
                    {"treasureNumber": 1, "treasureId": 47}, {"treasureNumber": 1, "treasureId": 48},
                    {"treasureNumber": 1, "treasureId": 49}, {"treasureNumber": 1, "treasureId": 50},
                    {"treasureNumber": 1, "treasureId": 51}, {"treasureNumber": 1, "treasureId": 52},
                    {"treasureNumber": 1, "treasureId": 53}, {"treasureNumber": 1, "treasureId": 54},
                    {"treasureNumber": 1, "treasureId": 55}, {"treasureNumber": 1, "treasureId": 56},
                    {"treasureNumber": 1, "treasureId": 57}, {"treasureNumber": 1, "treasureId": 58},
                    {"treasureNumber": 1, "treasureId": 59}, {"treasureNumber": 1, "treasureId": 60},
                    {"treasureNumber": 1, "treasureId": 61}, {"treasureNumber": 1, "treasureId": 62},
                    {"treasureNumber": 1, "treasureId": 63}, {"treasureNumber": 1, "treasureId": 64},
                    {"treasureNumber": 1, "treasureId": 65}, {"treasureNumber": 1, "treasureId": 66},
                    {"treasureNumber": 1, "treasureId": 67}, {"treasureNumber": 1, "treasureId": 68},
                    {"treasureNumber": 1, "treasureId": 69}, {"treasureNumber": 1, "treasureId": 70},
                    {"treasureNumber": 1, "treasureId": 71}, {"treasureNumber": 1, "treasureId": 72},
                    {"treasureNumber": 1, "treasureId": 73}, {"treasureNumber": 1, "treasureId": 74},
                    {"treasureNumber": 1, "treasureId": 75}, {"treasureNumber": 1, "treasureId": 76},
                    {"treasureNumber": 1, "treasureId": 77}, {"treasureNumber": 1, "treasureId": 78},
                    {"treasureNumber": 1, "treasureId": 79}, {"treasureNumber": 1, "treasureId": 80},
                    {"treasureNumber": 1, "treasureId": 81}, {"treasureNumber": 1, "treasureId": 82},
                    {"treasureNumber": 1, "treasureId": 83}, {"treasureNumber": 1, "treasureId": 84},
                    {"treasureNumber": 1, "treasureId": 85}, {"treasureNumber": 1, "treasureId": 86},
                    {"treasureNumber": 1, "treasureId": 87}, {"treasureNumber": 1, "treasureId": 88},
                    {"treasureNumber": 1, "treasureId": 89}, {"treasureNumber": 1, "treasureId": 90},
                    {"treasureNumber": 1, "treasureId": 91}, {"treasureNumber": 1, "treasureId": 92},
                    {"treasureNumber": 1, "treasureId": 93}, {"treasureNumber": 1, "treasureId": 94},
                    {"treasureNumber": 1, "treasureId": 95}, {"treasureNumber": 1, "treasureId": 96},
                    {"treasureNumber": 1, "treasureId": 97}, {"treasureNumber": 1, "treasureId": 98},
                    {"treasureNumber": 1, "treasureId": 99}, {"treasureNumber": 1, "treasureId": 100},
                    {"treasureNumber": 1, "treasureId": 101}, {"treasureNumber": 1, "treasureId": 102},
                    {"treasureNumber": 1, "treasureId": 103}, {"treasureNumber": 1, "treasureId": 104},
                    {"treasureNumber": 1, "treasureId": 105}, {"treasureNumber": 1, "treasureId": 106},
                    {"treasureNumber": 1, "treasureId": 107}, {"treasureNumber": 1, "treasureId": 108},
                    {"treasureNumber": 1, "treasureId": 109}, {"treasureNumber": 1, "treasureId": 110},
                    {"treasureNumber": 1, "treasureId": 111}, {"treasureNumber": 1, "treasureId": 112},
                    {"treasureNumber": 1, "treasureId": 113}, {"treasureNumber": 1, "treasureId": 114},
                    {"treasureNumber": 1, "treasureId": 115}, {"treasureNumber": 1, "treasureId": 116},
                    {"treasureNumber": 1, "treasureId": 117}]

# 图腾数据列表，勿动
# Totem data list, do not modify
TOTEM_LIST = {
    "totemAyLevel": "奥义图腾",
    "totemBwLevel": "宝物图腾",
    "totemCfLevel": "财富图腾",
    "totemDjLevel": "等级图腾",
    "totemDzLevel": "锻造图腾",
    "totemFyLevel": "防御图腾",
    "totemJhLevel": "进化图腾",
    "totemMhLevel": "蛮荒图腾",
    "totemMlLevel": "魔力图腾",
    "totemSdLevel": "速度图腾",
    "totemSjLevel": "时间图腾",
    "totemSmLevel": "生命图腾",
    "totemSwLevel": "死亡图腾",
    "totemYxLevel": "英雄图腾",
    "totemZfLevel": "祝福图腾"
}

EQUIPMENT_LIST = {
    "heroEquipmentHead": "遗物-尘封的皮帽🎩",
    "heroEquipmentArmor": "遗物-尘封的铠甲🧥",
    "heroEquipmentLegguard": "遗物-尘封的护腕  ",
    "heroEquipmentLeg": "遗物-尘封的护腿  ",
    "heroEquipmentShoes": "遗物-尘封的皮鞋👞",
    "heroEquipmentMainweapon": "遗物-尘封的长剑  ",
    "heroEquipmentSpeciaiweapon": "遗物-尘封的匕首🗡 "
}
# 宝物数据列表，勿动
# Treasure data list, do not modify
TREASURES_LIST = [
    ["modifier_treasure_beast_magic", "N-幻兽大师1"],
    ["modifier_treasure_beasts_royal", "N-御兽大师2"],
    ["modifier_treasure_red_pill", "N-红色药丸3"],
    ["modifier_treasure_blue_pill", "N-蓝色药丸4"],
    ["modifier_treasure_green_pill", "N-绿色药丸5"],
    ["modifier_treasure_extra_exp", "N-经验加3 6"],
    ["modifier_treasure_goodbyes", "N-告辞7"],
    ["modifier_treasure_stone_ghost_mask", "N-石鬼面具8"],
    ["modifier_treasure_evil_mask", "N-邪恶面具9"],
    ["modifier_treasure_risto_vault", "N-瑞斯托王庭金库10"],
    ["modifier_treasure_beerbung", "N-啤酒桶盖11"],
    ["modifier_treasure_leviathan_skin", "N-利维坦外壳12"],
    ["modifier_treasure_blackmail", "N-碰瓷13"],
    ["modifier_treasure_lost_mirror", "N-遗失之物：残破小镜14"],
    ["modifier_treasure_holiday_beach_shorts", "N-休假用品：沙滩裤15"],
    ["modifier_treasure_holiday_aloha_shirt", "N-休假用品：夏威夷衬衫16"],
    ["modifier_treasure_legion_flag", "N-军团旗帜17"],
    ["modifier_treasure_legion_drum", "N-军团战鼓18"],
    ["modifier_treasure_legion_mystique", "N-军团秘法19"],
    ["modifier_treasure_legion_arcanum", "N-军团秘药20"],
    ["modifier_treasure_protect_weak", "N-捍卫弱者21"],
    ["modifier_treasure_feast", "N-盛宴22"],
    ["modifier_treasure_lost_pen", "N-遗失之物：无墨之笔23"],
    ["modifier_treasure_lost_stick", "N-遗失之物：折断的拐杖24"],
    ["modifier_treasure_lost_book", "N-遗失之物：残缺的书籍25"],
    ["modifier_treasure_lost_knife", "N-遗失之物：生锈的小刀26"],
    ["modifier_treasure_lost_armor", "N-遗失之物：腐蚀护甲27"],
    ["modifier_treasure_wile", "N-狡诈计谋28"],
    ["modifier_treasure_selfish_doctor", "N-自私医师29"],
    ["modifier_treasure_small_gold_bag", "N-小金袋30"],
    ["modifier_treasure_risto_heraldry", "N-瑞斯托纹章31"],
    ["modifier_treasure_sacrificial_wristband", "N-牺牲护腕32"],
    ["modifier_treasure_emperor_qin", "N-我，秦始皇，打钱33"],
    ["modifier_treasure_tolerance", "N-隐忍34"],
    ["modifier_treasure_matrilocal", "N-赘婿35"],
    ["modifier_treasure_no_number", "R-RNM退钱36"],
    ["modifier_treasure_nuyi", "R-怒意37"],
    ["modifier_treasure_finally_ability", "R-最后的查克拉38"],
    ["modifier_treasure_money_power", "R-金钱就是力量39"],
    ["modifier_treasure_decay_mana", "R-腐朽圣剑40"],
    ["modifier_treasure_holy_cloak", "R-神圣斗篷41"],
    ["modifier_treasure_devil_earing", "R-恶魔耳钉42"],
    ["modifier_treasure_stone_hall_city_spear", "R-石堂城长枪43"],
    ["modifier_treasure_stone_hall_city_cloak", "R-石堂城斗篷44"],
    ["modifier_treasure_stone_hall_city_armor", "R-石堂城板甲45"],
    ["modifier_treasure_devil_transaction", "R-恶魔交易46"],
    ["modifier_treasure_assassin_secret", "R-刺客秘籍47"],
    ["modifier_treasure_brave_the_shield", "R-英勇盾牌48"],
    ["modifier_treasure_aghanim_crystal", "R-阿哈利姆结晶49"],
    ["modifier_treasure_pot_of_greed", "SR-强欲之壶50"],
    ["modifier_treasure_wizardry_mask", "R-巫术面具51"],
    ["modifier_treasure_rapid_bayonet", "N-疾风之刺52"],
    ["modifier_treasure_rapid_dagger", "R-疾风之匕53"],
    ["modifier_treasure_rapid_sword", "SR-疾风之剑54"],
    ["modifier_treasure_titan_armet", "N-泰坦头盔55"],
    ["modifier_treasure_titan_hammer", "R-泰坦战锤56"],
    ["modifier_treasure_titan_shield", "SR-泰坦神盾57"],
    ["modifier_treasure_abyss_orb", "N-深渊宝珠58"],
    ["modifier_treasure_abyss_sceptre", "R-深渊权杖59"],
    ["modifier_treasure_abyss_law", "SR-深渊法典60"],
    ["modifier_treasure_dragon_king_come_back", "SSR-龙王归来61"],
    ["modifier_treasure_nenglipengzhang", "SSR-能力膨胀62"],
    ["modifier_treasure_so_long", "N-听说名字取得长的宝物都很厉害63"],
    ["modifier_treasure_so_short", "N-短64"],
    ["modifier_treasure_bloodthirster", "N-饮血剑65"],
    ["modifier_treasure_bloodaxe", "R-饮血斧66"],
    ["modifier_treasure_bloodknife", "SR-饮血刀67"],
    ["modifier_treasure_intimidate", "N-恫吓68"],
    ["modifier_treasure_turbulence_mana", "SSR-法力乱流69"],
    ["modifier_treasure_five_thousand_exp", "R-5000经验70"],
    ["modifier_treasure_holiday_beach_slippers", "R-休假用品：沙滩拖鞋71"],
    ["modifier_treasure_holiday_sunglasses", "R-休假用品：墨镜72"],
    ["modifier_treasure_holiday_icecola", "R-休假用品：冰可乐73"],
    ["modifier_treasure_aghanim_scepter", "R-阿哈利姆神杖74"],
    ["modifier_treasure_three_phase_power_s", "R-三项碎片【上】75"],
    ["modifier_treasure_three_phase_power_a", "R-三项碎片【中】76"],
    ["modifier_treasure_three_phase_power_i", "R-三项碎片【下】77"],
    ["modifier_treasure_apocalypse_a", "R-启示录【上】78"],
    ["modifier_treasure_apocalypse_b", "R-启示录【中】79"],
    ["modifier_treasure_apocalypse_c", "R-启示录【下】80"],
    ["modifier_treasure_taiji_disciples", "N-太极门徒81"],
    ["modifier_treasure_taiji_intermediate", "R-太极大师82"],
    ["modifier_treasure_taiji_master", "SR-太极宗师83"],
    ["modifier_treasure_mhzl", "R-蛮荒之力84"],
    ["modifier_treasure_ltzl", "R-雷霆之力85"],
    ["modifier_treasure_xwzl", "R-虚无之力86"],
    ["modifier_treasure_smallmoney", "R-富二代87"],
    ["modifier_treasure_mhll", "SR-蛮荒灵力88"],
    ["modifier_treasure_ltll", "SR-雷霆灵力89"],
    ["modifier_treasure_xwll", "SR-虚无灵力90"],
    ["modifier_treasure_moremoney", "SR-大富翁91"],
    ["modifier_treasure_mhsl", "SSR-蛮荒神力92"],
    ["modifier_treasure_ltsl", "SSR-雷霆神力93"],
    ["modifier_treasure_xwsl", "SSR-虚无神力94"],
    ["modifier_treasure_gfatmoney", "SSR-G胖的钱包95"],
    ["modifier_treasure_back_off_a", "R-手动挡96"],
    ["modifier_treasure_back_off_b", "R-自动挡97"],
    ["modifier_treasure_back_off_c", "SSR-请注意,倒车98"],
    ["modifier_treasure_sublime_alchemist", "SSR-土豪升华卡99"],
    ["modifier_treasure_sublime_omniknight", "SSR-金蛋100"],
    ["modifier_treasure_sublime_phantom_assassin", "SSR-守望者101"],
    ["modifier_treasure_sublime_rattletrap", "SSR-坏心眼102"],
    ["modifier_treasure_sublime_shredder", "SSR-兵营103"],
    ["modifier_treasure_sublime_skeleton_king", "SSR-支援小炮104"],
    ["modifier_treasure_sublime_templar_assassin", "SSR-主角105"],
    ["modifier_treasure_sublime_treant", "SSR-代码哥106"],
    ["modifier_treasure_sublime_visage", "SSR-超级士兵107"],
    ["modifier_treasure_sublime_wisp", "SSR-黑洞108"],
    ["modifier_treasure_speed_fire", "R-109"],
    ["modifier_treasure_double_fire", "SR-110"],
    ["modifier_treasure_goldmon_attribute_one", "SR-金币怪悬赏令111"],
    ["modifier_treasure_goldmon_attribute_two", "SR-金币怪杀手112"],
    ["modifier_treasure_midas_collection", "SR-迈达斯的珍藏113"],
    ["modifier_treasure_more", "R- 莫多114"],
    ["modifier_treasure_more_more", "SR-莫多莫多115"],
    ["modifier_treasure_king_brilliant", "R-王者辉煌116"],
    ["modifier_treasure_king_glory", "SR-王者荣耀117"]
]
